# Mod3_Final Assessment - Data Exploration, Cleaning and Statistical Analysis

In this assessment, I work with two datasets related to an airline loyalty program. The goal is to explore their structure, identify data quality issues such as missing values or inconsistencies, and prepare the information for further statistical analysis and visualization.

The first dataset contains monthly flight activity, including flights booked, distance flown, and loyalty points. The second dataset contains customer profile information, such as location, education, salary, marital status, and loyalty program details.

As a first step, I perform an initial exploration of both datasets to understand their structure, review data types, detect null values and duplicates, and generate descriptive statistics. Then, I merge both datasets using the customer identifier in order to create a complete dataset for the next phases of the assessment.

After the exploration phase, a data cleaning process is carried out to ensure the quality and consistency of the dataset. This includes handling missing values in key variables, verifying the coherence of the data, and performing necessary transformations such as adjusting data types or correcting inconsistencies. These steps ensure that the dataset is properly prepared for statistical analysis.

## 1. Initial Exploration

In [4]:
# Import libraries

import pandas as pd
import numpy as np

# Display all columns when printing DataFrames
pd.set_option('display.max_columns', None)

In [5]:
# Load the first dataset: Customer Flight Activity

df1 = pd.read_csv("../files/raw/Customer Flight Activity.csv")
df1.head()

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
0,100018,2017,1,3,0,3,1521,152.0,0,0
1,100102,2017,1,10,4,14,2030,203.0,0,0
2,100140,2017,1,6,0,6,1200,120.0,0,0
3,100214,2017,1,0,0,0,0,0.0,0,0
4,100272,2017,1,0,0,0,0,0.0,0,0

In [6]:
# Check the size of the first dataset

print(f"Customer Flight Activity contains {df1.shape[0]} rows and {df1.shape[1]} columns.")

Customer Flight Activity contains 405624 rows and 10 columns.

In [7]:
# Get general information about the first dataset

df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 405624 entries, 0 to 405623
Data columns (total 10 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Loyalty Number               405624 non-null  int64
 1   Year                         405624 non-null  int64
 2   Month                        405624 non-null  int64
 3   Flights Booked               405624 non-null  int64
 4   Flights with Companions      405624 non-null  int64
 5   Total Flights                405624 non-null  int64
 6   Distance                     405624 non-null  int64
 7   Points Accumulated           405624 non-null  float64
 8   Points Redeemed              405624 non-null  int64
 9   Dollar Cost Points Redeemed  405624 non-null  int64
dtypes: float64(1), int64(9)
memory usage: 30.9 MB

In [8]:
# Analyze each column in the first dataset

print("COLUMN ANALYSIS\n")

for column in df1.columns:
    print("Column: ", column)
    print("Data type: ", df1[column].dtype)
    print(f"Null percentage: {round(df1[column].isna().mean() * 100, 2)}%")
    print("Unique values: ", df1[column].unique())
    print("Number of unique values: ", df1[column].nunique())
    print("----------------------\n")

COLUMN ANALYSIS

Column:  Loyalty Number
Data type:  int64
Null percentage: 0.0%
Unique values:  [100018 100102 100140 ... 999731 999788 999891]
Number of unique values:  16737
----------------------

Column:  Year
Data type:  int64
Null percentage: 0.0%
Unique values:  [2017 2018]
Number of unique values:  2
----------------------

Column:  Month
Data type:  int64
Null percentage: 0.0%
Unique values:  [ 1  9  2  3 11  4  5  7  6  8 10 12]
Number of unique values:  12
----------------------

Column:  Flights Booked
Data type:  int64
Null percentage: 0.0%
Unique values:  [ 3 10  6  0  8 11  9  4  7  5  2  1 12 13 14 16 15 17 18 19 20 21]
Number of unique values:  22
----------------------

Column:  Flights with Companions
Data type:  int64
Null percentage: 0.0%
Unique values:  [ 0  4  7  1  6  3  5  2 10  8  9 11]
Number of unique values:  12
----------------------

Column:  Total Flights
Data type:  int64
Null percentage: 0.0%
Unique values:  [ 3 14  6  0 15 11 12 10  8  9  7  5 16  2  1 17 13 22  4 19 18 21 26 20
 23 25 27 24 28 30 29 31 32]
Number of unique values:  33
----------------------

Column:  Distance
Data type:  int64
Null percentage: 0.0%
Unique values:  [1521 2030 1200 ... 1217  617 4135]
Number of unique values:  4746
----------------------

Column:  Points Accumulated
Data type:  float64
Null percentage: 0.0%
Unique values:  [152.   203.   120.   ...  18.75 601.   626.  ]
Number of unique values:  1549
----------------------

Column:  Points Redeemed
Data type:  int64
Null percentage: 0.0%
Unique values:  [  0 341 364 310 445 312 343 366 389 292 447 324 456 409 436 327 322 291
 323 300 290 309 325 386 321 363 340 670 443 517 444 328 344 367 313 333
 293 449 297 455 372 356 405 381 466 419 369 352 482 335 329 305 415 396
 317 348 314 334 350 330 318 298 420 336 471 680 441 353 484 301 374 417
 501 299 398 307 368 306 347 439 395 481 337 382 426 373 399 424 326 392
 438 467 480 448 308 400 376 375 460 339 385 611 431 320 362 404 442 410
 361 319 435 414 464 477 315 485 370 421 349 371 416 496 510 667 465 434
 346 487 408 500 360 378 345 358 479 380 411 491 505 446 425 476 393 418
 332 401 454 303 594 506 355 302 403 379 437 561 483 597 391 562 342 407
 490 468 488 457 365 357 463 388 413 351 462 440 493 507 338 377 428 525
 390 473 359 423 519 453 522 429 450 383 469 402 354 422 458 384 656 461
 427 478 523 719 538 515 394 472 433 387 540 530 498 512 452 311 470 541
 331 570 527 658 494 638 486 509 316 492 536 502 551 504 304 296 294 495
 432 526 459 589 529 586 537 503 552 779 516 639 474 547 542 557 406 563
 511 518 532 553 508 560 676 716 593 513 499 566 497 546 451 533 489 708
 531 567 521 412 430 610 528 556 582 720 397 578 772 571 534 539 576 585
 520 601 598 630 524 588 550 514 573 544 669 577 580 591 614 574 579 595
 618 776 548 602 543 581 572 607 603 564 620 615 636 575 584 559 648 590
 545 627 608 568 625 637 632 650 600 613 621 535 587 475 592 624 619 554
 583 628 558 664 789 635 617 699 604 646 659 616 704 569 626 609 751 599
 644 800 677 666 596 612 629 657 675 702 683 633 811 688 565 706 605 549
 662 660 295 673 555 631 715 651 697 792 678 655 707 668 687 622 642 781
 695 711 701 721 623 693 692 640 665 684 745 808 746 749 694 643 725 850
 703 726 691 740 737 689 765 649 690 661 696 682 700 750 771 798 710 736
 757 743 654 758 647 606 718 739 814 761 783 679 766 777 799 723 653 730
 681 760 793 742 685 734 839 782 735 756 795 728 780 802 815 851 820 770
 705 738 645 686 755 754 778 671 634 762 784 717 797 744 672 768 790 741
 824 748 674 825 794 845 827 801 714 731 724 876 747 663 709 823 791 804
 832 698 727 833 810 864 753 840 722 641 822 834 844 865 869 733 828 773
 713 821 849 767 759 729 803 838 775 818 843 830 847 872 809 786 812 785
 841 752 712 816 289 652 787 852 848 769 846 870 871 796 807 774 805 763
 806 836 837 857 813 873 732 826 858 817 829 819 866 842 861 855 831 875
 868 835 764 862 874 860 863 854 788 867 859]
Number of unique values:  587
----------------------

Column:  Dollar Cost Points Redeemed
Data type:  int64
Null percentage: 0.0%
Unique values:  [ 0 28 30 25 36 32 24 26 37 33 35 27 31 54 42 29 38 34 39 55 41 49 40 48
 45 53 58 44 43 46 52 47 63 57 62 51 50 64 56 61 65 60 68 59 66 69 67 71
 70]
Number of unique values:  49
----------------------

After this initial exploration of the Customer Flight Activity dataset, several points can be highlighted:

- There are no missing values in this dataset.
- All variables are numeric.
- None of the columns are constant, since all of them contain more than one unique value.
- Most columns are stored as integers, while **Points Accumulated** is stored as a float. This may be acceptable depending on how points are calculated, although it should be reviewed during the cleaning phase.

In [9]:
# Check for duplicated rows in the first dataset

print(f"Customer Flight Activity contains {df1.duplicated().sum()} duplicated entries.")
df1[df1.duplicated()]

Customer Flight Activity contains 1864 duplicated entries.

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
42,101902,2017,1,0,0,0,0,0.0,0,0
227,112142,2017,1,0,0,0,0,0.0,0,0
478,126100,2017,1,0,0,0,0,0.0,0,0
567,130331,2017,1,0,0,0,0,0.0,0,0
660,135421,2017,1,0,0,0,0,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...
404668,949628,2018,12,0,0,0,0,0.0,0,0
404884,960050,2018,12,0,0,0,0,0.0,0,0
405111,971370,2018,12,0,0,0,0,0.0,0,0
405410,988392,2018,12,0,0,0,0,0.0,0,0
405437,989528,2018,12,0,0,0,0,0.0,0,0

In [10]:
# Descriptive statistics for the (numeric) variables in the first dataset

df1.describe().T

,count,mean,std,min,25%,50%,75%,max
Loyalty Number,405624.0,550037.873084,258935.286969,100018.0,326961.00,550834.0,772194.00,999986.0
Year,405624.0,2017.500000,0.500001,2017.0,2017.00,2017.5,2018.00,2018.0
Month,405624.0,6.500000,3.452057,1.0,3.75,6.5,9.25,12.0
Flights Booked,405624.0,4.115052,5.225518,0.0,0.00,1.0,8.00,21.0
Flights with Companions,405624.0,1.031805,2.076869,0.0,0.00,0.0,1.00,11.0
Total Flights,405624.0,5.146858,6.521227,0.0,0.00,1.0,10.00,32.0
Distance,405624.0,1208.880059,1433.155320,0.0,0.00,488.0,2336.00,6293.0
Points Accumulated,405624.0,123.692721,146.599831,0.0,0.00,50.0,239.00,676.5
Points Redeemed,405624.0,30.696872,125.486049,0.0,0.00,0.0,0.00,876.0
Dollar Cost Points Redeemed,405624.0,2.484503,10.150038,0.0,0.00,0.0,0.00,71.0

The dataset shows a highly skewed distribution across most variables, with many customers showing low activity and a smaller group reaching much higher values.

**Flights Booked** has a low median (1) compared with its mean (around 4), which suggests that most customers book few flights, while a small group books much more frequently. A similar pattern can be seen in **Distance** and **Points Accumulated**, where dispersion is high and some extreme values appear.

In contrast, **Points Redeemed** and **Dollar Cost Points Redeemed** are mostly concentrated around zero, suggesting that many customers do not frequently redeem their points.

Overall, the data suggests that customer activity is unevenly distributed, with a minority of highly active customers generating a large share of the activity.

In [11]:
# Load the second dataset: Customer Loyalty History

df2 = pd.read_csv("../files/raw/Customer Loyalty History.csv")
df2.head()

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
0,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,NaN,NaN
1,549612,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,NaN,Divorced,Star,3839.61,Standard,2016,3,NaN,NaN
2,429460,Canada,British Columbia,Vancouver,V6E 3D9,Male,College,NaN,Single,Star,3839.75,Standard,2014,7,2018.0,1.0
3,608370,Canada,Ontario,Toronto,P1W 1K4,Male,College,NaN,Single,Star,3839.75,Standard,2013,2,NaN,NaN
4,530508,Canada,Quebec,Hull,J8Y 3Z5,Male,Bachelor,103495.0,Married,Star,3842.79,Standard,2014,10,NaN,NaN

In [12]:
# Check the size of the second dataset

print(f"Customer Loyalty History contains {df2.shape[0]} rows and {df2.shape[1]} columns.")

Customer Loyalty History contains 16737 rows and 16 columns.

In [13]:
# Get general information about the second dataset

df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 16737 entries, 0 to 16736
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Loyalty Number      16737 non-null  int64
 1   Country             16737 non-null  str
 2   Province            16737 non-null  str
 3   City                16737 non-null  str
 4   Postal Code         16737 non-null  str
 5   Gender              16737 non-null  str
 6   Education           16737 non-null  str
 7   Salary              12499 non-null  float64
 8   Marital Status      16737 non-null  str
 9   Loyalty Card        16737 non-null  str
 10  CLV                 16737 non-null  float64
 11  Enrollment Type     16737 non-null  str
 12  Enrollment Year     16737 non-null  int64
 13  Enrollment Month    16737 non-null  int64
 14  Cancellation Year   2067 non-null   float64
 15  Cancellation Month  2067 non-null   float64
dtypes: float64(4), int64(3), str(9)
memory usage: 2.0 MB

In [14]:
# Analyze each column in the second dataset

print("COLUMN ANALYSIS\n")

for column in df2.columns:
    print("Column: ", column)
    print("Data type: ", df2[column].dtype)
    print(f"Null percentage: {round(df2[column].isna().mean() * 100, 2)}%")
    print("Unique values: ", df2[column].unique())
    print("Number of unique values: ", df2[column].nunique())
    print("----------------------\n")

COLUMN ANALYSIS

Column:  Loyalty Number
Data type:  int64
Null percentage: 0.0%
Unique values:  [480934 549612 429460 ... 776187 906428 652627]
Number of unique values:  16737
----------------------

Column:  Country
Data type:  str
Null percentage: 0.0%
Unique values:  <StringArray>
['Canada']
Length: 1, dtype: str
Number of unique values:  1
----------------------

Column:  Province
Data type:  str
Null percentage: 0.0%
Unique values:  <StringArray>
[             'Ontario',              'Alberta',     'British Columbia',
               'Quebec',                'Yukon',        'New Brunswick',
             'Manitoba',          'Nova Scotia',         'Saskatchewan',
         'Newfoundland', 'Prince Edward Island']
Length: 11, dtype: str
Number of unique values:  11
----------------------

Column:  City
Data type:  str
Null percentage: 0.0%
Unique values:  <StringArray>
[       'Toronto',       'Edmonton',      'Vancouver',           'Hull',
     'Whitehorse',        'Trenton',       'Montreal',   'Dawson Creek',
    'Quebec City',    'Fredericton',         'Ottawa',      'Tremblant',
        'Calgary',    'Thunder Bay',       'Whistler',    'Peace River',
       'Winnipeg',        'Sudbury', 'West Vancouver',        'Halifax',
         'London',         'Regina',        'Kelowna',     'St. John's',
       'Victoria',       'Kingston',          'Banff',        'Moncton',
  'Charlottetown']
Length: 29, dtype: str
Number of unique values:  29
----------------------

Column:  Postal Code
Data type:  str
Null percentage: 0.0%
Unique values:  <StringArray>
['M2Z 4K1', 'T3G 6Y6', 'V6E 3D9', 'P1W 1K4', 'J8Y 3Z5', 'Y2K 6R0', 'P5S 6R4',
 'K8V 4B2', 'H2Y 2W2', 'M8Y 4K8', 'U5I 4F1', 'G1B 3L5', 'H4G 3T4', 'M2M 7K8',
 'M2M 6J7', 'E3B 2H2', 'M1R 4K3', 'T9G 1W3', 'H2Y 4R4', 'V5R 1W3', 'P1L 8X8',
 'K1F 2R2', 'H5Y 2S9', 'V1E 4R6', 'H2T 2J6', 'T3E 2V9', 'H2T 9K8', 'K8T 5M5',
 'V6T 1Y8', 'P2T 6G3', 'T9O 2W2', 'V6E 3Z3', 'R6Y 4T5', 'M5V 1G5', 'V6V 8Z3',
 'B3J 9S2', 'M5B 3E4', 'R2C 0M5', 'S6J 3G0', 'M2P 4F6', 'P1J 8T7', 'V09 2E9',
 'A1C 6H9', 'V10 6T5', 'B3C 2M8', 'M9K 2P4', 'T4V 1D4', 'R3R 3T4', 'S1J 3C5',
 'E1A 2A7', 'K1G 4Z0', 'H3T 8L4', 'C1A 6E8', 'H3J 5I6', 'M3R 4K8']
Length: 55, dtype: str
Number of unique values:  55
----------------------

Column:  Gender
Data type:  str
Null percentage: 0.0%
Unique values:  <StringArray>
['Female', 'Male']
Length: 2, dtype: str
Number of unique values:  2
----------------------

Column:  Education
Data type:  str
Null percentage: 0.0%
Unique values:  <StringArray>
['Bachelor', 'College', 'Master', 'High School or Below', 'Doctor']
Length: 5, dtype: str
Number of unique values:  5
----------------------

Column:  Salary
Data type:  float64
Null percentage: 25.32%
Unique values:  [ 83236.     nan 103495. ...  76178.  91970. -57297.]
Number of unique values:  5890
----------------------

Column:  Marital Status
Data type:  str
Null percentage: 0.0%
Unique values:  <StringArray>
['Married', 'Divorced', 'Single']
Length: 3, dtype: str
Number of unique values:  3
----------------------

Column:  Loyalty Card
Data type:  str
Null percentage: 0.0%
Unique values:  <StringArray>
['Star', 'Aurora', 'Nova']
Length: 3, dtype: str
Number of unique values:  3
----------------------

Column:  CLV
Data type:  float64
Null percentage: 0.0%
Unique values:  [ 3839.14  3839.61  3839.75 ... 44771.3  50568.26 61134.68]
Number of unique values:  7984
----------------------

Column:  Enrollment Type
Data type:  str
Null percentage: 0.0%
Unique values:  <StringArray>
['Standard', '2018 Promotion']
Length: 2, dtype: str
Number of unique values:  2
----------------------

Column:  Enrollment Year
Data type:  int64
Null percentage: 0.0%
Unique values:  [2016 2014 2013 2012 2015 2018 2017]
Number of unique values:  7
----------------------

Column:  Enrollment Month
Data type:  int64
Null percentage: 0.0%
Unique values:  [ 2  3  7 10  5  6 12  1 11  8  4  9]
Number of unique values:  12
----------------------

Column:  Cancellation Year
Data type:  float64
Null percentage: 87.65%
Unique values:  [  nan 2018. 2015. 2017. 2014. 2016. 2013.]
Number of unique values:  6
----------------------

Column:  Cancellation Month
Data type:  float64
Null percentage: 87.65%
Unique values:  [nan  1. 12.  4.  2.  7. 11.  5.  6. 10.  8.  9.  3.]
Number of unique values:  12
----------------------

After this initial exploration of the Customer Loyalty History dataset, the following points can be highlighted:

- This dataset contains missing values.
    - Some variables, such as **Cancellation Year**, **Cancellation Month**, and **Salary**, will need special attention during the cleaning phase due to the presence of null values.
- **Country** is a constant variable, since all records correspond to Canada.
- The dataset includes both numeric and categorical variables, which will require different types of analysis.

In [15]:
# Calculate the percentage of null values in the second dataset

nulls = round((df2.isna().sum() / df2.shape[0]) * 100, 2)
nulls[nulls > 0].sort_values(ascending=False)

Cancellation Year     87.65
Cancellation Month    87.65
Salary                25.32
dtype: float64

**Cancellation Year** and **Cancellation Month** have a high percentage of missing values (87.65%), which likely indicates that those customers are still active in the loyalty program and have not cancelled their membership.

**Salary** also shows a relevant proportion of missing values (25.32%), so this variable may require further treatment before analysis.

In [16]:
# Check for duplicated rows in the second dataset

print(f"Customer Loyalty History contains {df2.duplicated().sum()} duplicated entries.")

Customer Loyalty History contains 0 duplicated entries.

In [17]:
# Check whether Loyalty Number is unique in the second dataset

df2["Loyalty Number"].duplicated().sum()

np.int64(0)

No duplicated customer IDs were found in **Loyalty Number**, which suggests that each row represents a unique customer profile in this dataset.

In [18]:
# Descriptive statistics for the numeric variables in the second dataset

df2.describe().T

,count,mean,std,min,25%,50%,75%,max
Loyalty Number,16737.0,549735.880445,258912.132453,100018.00,326603.00,550434.00,772019.00,999986.00
Salary,12499.0,79245.609409,35008.297285,-58486.00,59246.50,73455.00,88517.50,407228.00
CLV,16737.0,7988.896536,6860.982280,1898.01,3980.84,5780.18,8940.58,83325.38
Enrollment Year,16737.0,2015.253211,1.979111,2012.00,2014.00,2015.00,2017.00,2018.00
Enrollment Month,16737.0,6.669116,3.398958,1.00,4.00,7.00,10.00,12.00
Cancellation Year,2067.0,2016.503145,1.380743,2013.00,2016.00,2017.00,2018.00,2018.00
Cancellation Month,2067.0,6.962748,3.455297,1.00,4.00,7.00,10.00,12.00

The numeric variables in this dataset show considerable variability, especially in **Salary** and **CLV**.

**Salary** presents a wide range of values, including some negative values, which may indicate data quality issues and should be reviewed during the cleaning phase. **CLV** also shows substantial dispersion, suggesting notable differences in customer value across the dataset.

**Enrollment Year**, **Enrollment Month**, **Cancellation Year**, and **Cancellation Month** mainly serve as temporal reference variables and will be more useful for contextual or segmented analysis than for direct numerical interpretation.

Overall, the numeric profile dataset includes some potentially useful business variables, but it also shows issues that should be addressed before deeper analysis.

In [19]:
# Descriptive statistics for the categorical variables in the second dataset

df2.describe(include="str").T

                 count unique       top   freq
Country          16737      1    Canada  16737
Province         16737     11   Ontario   5404
City             16737     29   Toronto   3351
Postal Code      16737     55   V6E 3D9    911
Gender           16737      2    Female   8410
Education        16737      5  Bachelor  10475
Marital Status   16737      3   Married   9735
Loyalty Card     16737      3      Star   7637
Enrollment Type  16737      2  Standard  15766

The dataset shows a fairly concentrated customer profile, with limited variability in some categorical variables.

All customers are from **Canada**, while **Ontario** and **Toronto** are the most frequent province and city, which suggests a geographic concentration. Gender is relatively balanced, although **Female** appears slightly more often.

Most customers have a **Bachelor's degree** and are **Married**, which indicates a fairly homogeneous demographic profile. In terms of the loyalty program, **Star** is the most common card type, and **Standard** is by far the most frequent enrollment type.

Overall, the customer base appears relatively similar in demographic and loyalty program characteristics, with clear concentration in some categories.

In [20]:
# We merge both datasets using "Loyalty Number" as the key, since it uniquely identifies each customer in both tables. This allows us to combine flight activity with customer profile information in a consistent and reliable way.

df = df1.merge(df2, on = "Loyalty Number")
df.head()

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
0,100018,2017,1,3,0,3,1521,152.0,0,0,Canada,Alberta,Edmonton,T9G 1W3,Female,Bachelor,92552.0,Married,Aurora,7919.20,Standard,2016,8,NaN,NaN
1,100102,2017,1,10,4,14,2030,203.0,0,0,Canada,Ontario,Toronto,M1R 4K3,Male,College,NaN,Single,Nova,2887.74,Standard,2013,3,NaN,NaN
2,100140,2017,1,6,0,6,1200,120.0,0,0,Canada,British Columbia,Dawson Creek,U5I 4F1,Female,College,NaN,Divorced,Nova,2838.07,Standard,2016,7,NaN,NaN
3,100214,2017,1,0,0,0,0,0.0,0,0,Canada,British Columbia,Vancouver,V5R 1W3,Male,Bachelor,63253.0,Married,Star,4170.57,Standard,2015,8,NaN,NaN
4,100272,2017,1,0,0,0,0,0.0,0,0,Canada,Ontario,Toronto,P1L 8X8,Female,Bachelor,91163.0,Divorced,Star,6622.05,Standard,2014,1,NaN,NaN

In [21]:
# Check the size of the merged dataset

print(f"Our final dataset contains {df.shape[0]} rows and {df.shape[1]} columns.")

Our final dataset contains 405624 rows and 25 columns.

In [22]:
# Check null values in the merged dataset

df_nulls = round((df.isna().sum() / df.shape[0]) * 100, 2)
df_nulls[df_nulls > 0].sort_values(ascending=False)

Cancellation Year     87.66
Cancellation Month    87.66
Salary                25.31
dtype: float64

After merging both datasets, the missing values observed in the customer profile variables remain consistent with the issues previously identified in the loyalty history dataset. No new structural problems appear to have been introduced by the merge.

In [23]:
# Before starting the cleaning phase, the merged dataset is saved to ensure reproducibility and to preserve the original combined structure of the data.

df.to_csv("../files/processed/merged_dataset_v1.csv", index=False)

## 2. Data Cleaning

In [24]:
# First, create a copy of our merged dataset for safety

df_copy = df.copy()

df_copy.head(2)

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
0,100018,2017,1,3,0,3,1521,152.0,0,0,Canada,Alberta,Edmonton,T9G 1W3,Female,Bachelor,92552.0,Married,Aurora,7919.20,Standard,2016,8,NaN,NaN
1,100102,2017,1,10,4,14,2030,203.0,0,0,Canada,Ontario,Toronto,M1R 4K3,Male,College,NaN,Single,Nova,2887.74,Standard,2013,3,NaN,NaN

We will start deleting or tratando our missing values.
If we check about next steps of this proyect, we don't need to use Cancellation Year or Cancellation Month for any visualization. So, we are going to check quickly if our hipothesis is right and there are nulls because they are still clients. If that, we will replace NaN for 0, to keep the data type.

Cancellation Year and Cancellation Month contain a high percentage of null values. These missing values do not indicate data quality issues, but rather that the customer has not cancelled their membership.

Since no further analysis involving cancellation dates is required, these null values are preserved as they carry meaningful information and do not need to be modified.

In [25]:
# Salary will be needed for further visualizations. We are going to analyze the missing values

df_copy["Salary"].describe()

count    302952.000000
mean      79268.825953
std       34992.133508
min      -58486.000000
25%       59262.000000
50%       73479.000000
75%       88612.000000
max      407228.000000
Name: Salary, dtype: float64

Salary contains missing values and some invalid negative values, which are not realistic for this variable.

In [26]:
# Analyzing negative values

df_copy[df_copy["Salary"] < 0]

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
293,115505,2017,1,0,0,0,0,0.0,0,0,Canada,Newfoundland,St. John's,A1C 6H9,Male,Bachelor,-10605.0,Married,Nova,5860.17,2018 Promotion,2018,4,NaN,NaN
961,152016,2017,1,0,0,0,0,0.0,0,0,Canada,Ontario,Toronto,P1J 8T7,Female,Bachelor,-58486.0,Married,Aurora,5067.21,2018 Promotion,2018,2,NaN,NaN
1740,194065,2017,1,0,0,0,0,0.0,0,0,Canada,Ontario,Sudbury,M5V 1G5,Female,Bachelor,-31911.0,Married,Nova,2888.85,2018 Promotion,2018,2,NaN,NaN
2111,212128,2017,1,3,0,3,1959,195.0,0,0,Canada,Ontario,Toronto,P2T 6G3,Male,Bachelor,-49001.0,Married,Nova,3130.68,2018 Promotion,2018,2,NaN,NaN
2464,232755,2017,1,0,0,0,0,0.0,0,0,Canada,British Columbia,Vancouver,V1E 4R6,Female,Bachelor,-46683.0,Single,Nova,4787.81,2018 Promotion,2018,3,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
400664,734647,2018,12,15,0,15,1440,144.0,0,0,Canada,Saskatchewan,Regina,S1J 3C5,Male,Bachelor,-46303.0,Married,Nova,11280.73,2018 Promotion,2018,4,NaN,NaN
401739,790475,2018,12,7,1,8,1056,105.0,0,0,Canada,Ontario,Trenton,K8V 4B2,Female,Bachelor,-34079.0,Married,Nova,12913.50,2018 Promotion,2018,2,NaN,NaN
403876,906428,2018,12,13,0,13,2912,291.0,0,0,Canada,Yukon,Whitehorse,Y2K 6R0,Male,Bachelor,-57297.0,Married,Star,10018.66,2018 Promotion,2018,4,NaN,NaN
404318,430398,2018,12,5,5,10,660,66.0,539,44,Canada,Newfoundland,St. John's,A1C 6H9,Male,Bachelor,-17534.0,Married,Nova,49423.80,2018 Promotion,2018,3,NaN,NaN
404881,959977,2018,12,14,6,20,4280,428.0,0,0,Canada,British Columbia,Vancouver,V5R 1W3,Female,Bachelor,-12497.0,Married,Aurora,9453.00,2018 Promotion,2018,3,NaN,NaN

480 entries contains negative values on Salary. As mentioned, negative salary values are considered data errors, so they are treated as missing values. Instead of modifying them arbitrarily, they are replaced with NaN and later imputed using a more reliable approach.

In [27]:
df_copy.loc[df_copy["Salary"] < 0, "Salary"] = np.nan

In [28]:
# Missing values are imputed using the median salary within each education group
# This approach allows for a more realistic estimation, as salary is likely to vary depending on the level of education, and the median is robust to outliers
# Median is preferred over the mean to reduce the impact of extreme values

df_copy["Salary"] = df_copy.groupby("Education")["Salary"].transform(lambda x: x.fillna(x.median()))